import Foundation

enum DrumVoice: String, CaseIterable {
  case kick, snare, hat, ohat, clap, rim, tom, perc
  var label: String {
    switch self {
    case .kick: return "Kick"
    case .snare: return "Snare"
    case .hat: return "Hat"
    case .ohat: return "Open Hat"
    case .clap: return "Clap"
    case .rim: return "Rim"
    case .tom: return "Tom"
    case .perc: return "Perc"
    }
  }
}

struct DrumHit { var step: Int; var voice: DrumVoice; var vel: Float }

struct DrumPattern: Identifiable {
  var id: String
  var name: String
  var feel: String
  var bars: Int
  var swing: Float
  var hits: [DrumHit]
}

enum DrumLibrary {
  static let all: [DrumPattern] = [
    DrumPattern(id: "floor", name: "Four on the Floor", feel: "House pulse", bars: 1, swing: 0.0, hits: [
      .init(step: 0, voice: .kick, vel: 1),
      .init(step: 4, voice: .kick, vel: 0.92),
      .init(step: 8, voice: .kick, vel: 1),
      .init(step: 12, voice: .kick, vel: 0.92),
      .init(step: 4, voice: .clap, vel: 0.85),
      .init(step: 12, voice: .clap, vel: 0.9),
      .init(step: 0, voice: .hat, vel: 0.55),
      .init(step: 2, voice: .hat, vel: 0.4),
      .init(step: 4, voice: .hat, vel: 0.55),
      .init(step: 6, voice: .hat, vel: 0.4),
      .init(step: 8, voice: .hat, vel: 0.55),
      .init(step: 10, voice: .hat, vel: 0.42),
      .init(step: 12, voice: .hat, vel: 0.55),
      .init(step: 14, voice: .hat, vel: 0.38),
      .init(step: 10, voice: .ohat, vel: 0.35),
    ]),
    DrumPattern(id: "pocket", name: "Tight Pocket", feel: "Dry studio", bars: 1, swing: 0.08, hits: [
      .init(step: 0, voice: .kick, vel: 1),
      .init(step: 6, voice: .kick, vel: 0.7),
      .init(step: 8, voice: .kick, vel: 0.88),
      .init(step: 4, voice: .snare, vel: 0.9),
      .init(step: 12, voice: .snare, vel: 0.95),
      .init(step: 0, voice: .hat, vel: 0.5),
      .init(step: 2, voice: .hat, vel: 0.32),
      .init(step: 4, voice: .hat, vel: 0.5),
      .init(step: 6, voice: .hat, vel: 0.3),
      .init(step: 8, voice: .hat, vel: 0.5),
      .init(step: 10, voice: .hat, vel: 0.28),
      .init(step: 12, voice: .hat, vel: 0.5),
      .init(step: 14, voice: .hat, vel: 0.34),
      .init(step: 10, voice: .rim, vel: 0.4),
    ]),
    DrumPattern(id: "boombap", name: "Boom Bap", feel: "Head-nod", bars: 1, swing: 0.18, hits: [
      .init(step: 0, voice: .kick, vel: 1),
      .init(step: 10, voice: .kick, vel: 0.85),
      .init(step: 4, voice: .snare, vel: 0.92),
      .init(step: 12, voice: .snare, vel: 1),
      .init(step: 7, voice: .snare, vel: 0.28),
      .init(step: 0, voice: .hat, vel: 0.45),
      .init(step: 2, voice: .hat, vel: 0.28),
      .init(step: 4, voice: .hat, vel: 0.42),
      .init(step: 6, voice: .hat, vel: 0.26),
      .init(step: 8, voice: .hat, vel: 0.45),
      .init(step: 10, voice: .hat, vel: 0.3),
      .init(step: 12, voice: .hat, vel: 0.4),
      .init(step: 14, voice: .hat, vel: 0.24),
    ]),
    DrumPattern(id: "break", name: "Breakbeat", feel: "Open break", bars: 2, swing: 0.06, hits: [
      .init(step: 0, voice: .kick, vel: 1),
      .init(step: 6, voice: .kick, vel: 0.8),
      .init(step: 10, voice: .kick, vel: 0.7),
      .init(step: 16, voice: .kick, vel: 1),
      .init(step: 22, voice: .kick, vel: 0.75),
      .init(step: 4, voice: .snare, vel: 0.9),
      .init(step: 12, voice: .snare, vel: 1),
      .init(step: 20, voice: .snare, vel: 0.9),
      .init(step: 28, voice: .snare, vel: 1),
      .init(step: 14, voice: .snare, vel: 0.35),
      .init(step: 26, voice: .snare, vel: 0.3),
      .init(step: 18, voice: .ohat, vel: 0.4),
      .init(step: 0, voice: .hat, vel: 0.48),
      .init(step: 2, voice: .hat, vel: 0.28),
      .init(step: 4, voice: .hat, vel: 0.48),
      .init(step: 6, voice: .hat, vel: 0.28),
      .init(step: 8, voice: .hat, vel: 0.48),
      .init(step: 10, voice: .hat, vel: 0.28),
      .init(step: 12, voice: .hat, vel: 0.48),
      .init(step: 14, voice: .hat, vel: 0.28),
      .init(step: 16, voice: .hat, vel: 0.48),
      .init(step: 18, voice: .hat, vel: 0.28),
      .init(step: 20, voice: .hat, vel: 0.48),
      .init(step: 22, voice: .hat, vel: 0.28),
      .init(step: 24, voice: .hat, vel: 0.48),
      .init(step: 26, voice: .hat, vel: 0.28),
      .init(step: 28, voice: .hat, vel: 0.48),
      .init(step: 30, voice: .hat, vel: 0.28),
    ]),
    DrumPattern(id: "halftime", name: "Half Time", feel: "Heavy drop", bars: 2, swing: 0.04, hits: [
      .init(step: 0, voice: .kick, vel: 1),
      .init(step: 16, voice: .kick, vel: 0.95),
      .init(step: 14, voice: .kick, vel: 0.45),
      .init(step: 8, voice: .snare, vel: 1),
      .init(step: 24, voice: .snare, vel: 1),
      .init(step: 26, voice: .rim, vel: 0.35),
      .init(step: 0, voice: .hat, vel: 0.35),
      .init(step: 4, voice: .hat, vel: 0.22),
      .init(step: 8, voice: .hat, vel: 0.4),
      .init(step: 12, voice: .hat, vel: 0.22),
      .init(step: 16, voice: .hat, vel: 0.35),
      .init(step: 20, voice: .hat, vel: 0.22),
      .init(step: 24, voice: .hat, vel: 0.4),
      .init(step: 28, voice: .hat, vel: 0.22),
      .init(step: 20, voice: .ohat, vel: 0.3),
      .init(step: 6, voice: .perc, vel: 0.4),
      .init(step: 22, voice: .perc, vel: 0.38),
    ]),
    DrumPattern(id: "shuffle", name: "Shuffle", feel: "Swung blues", bars: 1, swing: 0.42, hits: [
      .init(step: 0, voice: .kick, vel: 1),
      .init(step: 8, voice: .kick, vel: 0.7),
      .init(step: 4, voice: .snare, vel: 0.82),
      .init(step: 12, voice: .snare, vel: 0.9),
      .init(step: 0, voice: .hat, vel: 0.5),
      .init(step: 2, voice: .hat, vel: 0.22),
      .init(step: 4, voice: .hat, vel: 0.45),
      .init(step: 6, voice: .hat, vel: 0.2),
      .init(step: 8, voice: .hat, vel: 0.5),
      .init(step: 10, voice: .hat, vel: 0.22),
      .init(step: 12, voice: .hat, vel: 0.45),
      .init(step: 14, voice: .hat, vel: 0.18),
      .init(step: 10, voice: .rim, vel: 0.3),
    ]),
    DrumPattern(id: "clave", name: "Latin Clave", feel: "3–2 son", bars: 2, swing: 0.05, hits: [
      .init(step: 0, voice: .kick, vel: 1),
      .init(step: 6, voice: .kick, vel: 0.75),
      .init(step: 12, voice: .kick, vel: 0.65),
      .init(step: 16, voice: .kick, vel: 0.9),
      .init(step: 22, voice: .kick, vel: 0.7),
      .init(step: 4, voice: .snare, vel: 0.35),
      .init(step: 12, voice: .snare, vel: 0.55),
      .init(step: 20, voice: .snare, vel: 0.4),
      .init(step: 28, voice: .snare, vel: 0.7),
      .init(step: 0, voice: .perc, vel: 0.85),
      .init(step: 3, voice: .perc, vel: 0.7),
      .init(step: 6, voice: .perc, vel: 0.8),
      .init(step: 10, voice: .perc, vel: 0.75),
      .init(step: 12, voice: .perc, vel: 0.8),
      .init(step: 16, voice: .perc, vel: 0.55),
      .init(step: 20, voice: .perc, vel: 0.5),
      .init(step: 24, voice: .perc, vel: 0.55),
      .init(step: 28, voice: .perc, vel: 0.5),
      .init(step: 0, voice: .hat, vel: 0.3),
      .init(step: 4, voice: .hat, vel: 0.28),
      .init(step: 8, voice: .hat, vel: 0.3),
      .init(step: 12, voice: .hat, vel: 0.28),
      .init(step: 16, voice: .hat, vel: 0.3),
      .init(step: 20, voice: .hat, vel: 0.28),
      .init(step: 24, voice: .hat, vel: 0.3),
      .init(step: 28, voice: .hat, vel: 0.28),
      .init(step: 8, voice: .tom, vel: 0.45),
      .init(step: 26, voice: .tom, vel: 0.5),
    ]),
    DrumPattern(id: "techno", name: "Techno Pulse", feel: "Hypnotic", bars: 1, swing: 0.0, hits: [
      .init(step: 0, voice: .kick, vel: 1),
      .init(step: 4, voice: .kick, vel: 1),
      .init(step: 8, voice: .kick, vel: 1),
      .init(step: 12, voice: .kick, vel: 1),
      .init(step: 0, voice: .hat, vel: 0.22),
      .init(step: 1, voice: .hat, vel: 0.16),
      .init(step: 2, voice: .hat, vel: 0.38),
      .init(step: 3, voice: .hat, vel: 0.16),
      .init(step: 4, voice: .hat, vel: 0.22),
      .init(step: 5, voice: .hat, vel: 0.16),
      .init(step: 6, voice: .hat, vel: 0.4),
      .init(step: 7, voice: .hat, vel: 0.16),
      .init(step: 8, voice: .hat, vel: 0.22),
      .init(step: 9, voice: .hat, vel: 0.16),
      .init(step: 10, voice: .hat, vel: 0.38),
      .init(step: 11, voice: .hat, vel: 0.16),
      .init(step: 12, voice: .hat, vel: 0.22),
      .init(step: 13, voice: .hat, vel: 0.16),
      .init(step: 14, voice: .hat, vel: 0.42),
      .init(step: 15, voice: .hat, vel: 0.18),
      .init(step: 14, voice: .ohat, vel: 0.28),
      .init(step: 4, voice: .clap, vel: 0.4),
      .init(step: 12, voice: .clap, vel: 0.55),
    ]),
    DrumPattern(id: "dilla", name: "Late Pocket", feel: "Drunk swing", bars: 1, swing: 0.28, hits: [
      .init(step: 0, voice: .kick, vel: 1),
      .init(step: 5, voice: .kick, vel: 0.55),
      .init(step: 11, voice: .kick, vel: 0.8),
      .init(step: 4, voice: .snare, vel: 0.78),
      .init(step: 12, voice: .snare, vel: 0.95),
      .init(step: 13, voice: .snare, vel: 0.22),
      .init(step: 0, voice: .hat, vel: 0.4),
      .init(step: 3, voice: .hat, vel: 0.22),
      .init(step: 4, voice: .hat, vel: 0.38),
      .init(step: 7, voice: .hat, vel: 0.18),
      .init(step: 8, voice: .hat, vel: 0.42),
      .init(step: 11, voice: .hat, vel: 0.2),
      .init(step: 12, voice: .hat, vel: 0.36),
      .init(step: 15, voice: .hat, vel: 0.16),
      .init(step: 6, voice: .rim, vel: 0.32),
    ]),
    DrumPattern(id: "garage", name: "UK Garage", feel: "Skip beat", bars: 2, swing: 0.22, hits: [
      .init(step: 0, voice: .kick, vel: 1),
      .init(step: 10, voice: .kick, vel: 0.85),
      .init(step: 16, voice: .kick, vel: 0.7),
      .init(step: 20, voice: .kick, vel: 0.9),
      .init(step: 4, voice: .snare, vel: 0.55),
      .init(step: 12, voice: .snare, vel: 0.95),
      .init(step: 28, voice: .snare, vel: 0.9),
      .init(step: 6, voice: .snare, vel: 0.25),
      .init(step: 22, voice: .rim, vel: 0.4),
      .init(step: 14, voice: .ohat, vel: 0.45),
      .init(step: 30, voice: .ohat, vel: 0.4),
      .init(step: 0, voice: .hat, vel: 0.28),
      .init(step: 2, voice: .hat, vel: 0.48),
      .init(step: 4, voice: .hat, vel: 0.28),
      .init(step: 6, voice: .hat, vel: 0.48),
      .init(step: 8, voice: .hat, vel: 0.28),
      .init(step: 10, voice: .hat, vel: 0.48),
      .init(step: 12, voice: .hat, vel: 0.28),
      .init(step: 14, voice: .hat, vel: 0.48),
      .init(step: 16, voice: .hat, vel: 0.28),
      .init(step: 18, voice: .hat, vel: 0.48),
      .init(step: 20, voice: .hat, vel: 0.28),
      .init(step: 22, voice: .hat, vel: 0.48),
      .init(step: 24, voice: .hat, vel: 0.28),
      .init(step: 26, voice: .hat, vel: 0.48),
      .init(step: 28, voice: .hat, vel: 0.28),
      .init(step: 30, voice: .hat, vel: 0.48),
    ]),
    DrumPattern(id: "brush", name: "Rim & Brush", feel: "Quiet room", bars: 1, swing: 0.14, hits: [
      .init(step: 0, voice: .kick, vel: 0.55),
      .init(step: 8, voice: .kick, vel: 0.4),
      .init(step: 4, voice: .rim, vel: 0.7),
      .init(step: 12, voice: .rim, vel: 0.8),
      .init(step: 10, voice: .rim, vel: 0.3),
      .init(step: 0, voice: .hat, vel: 0.28),
      .init(step: 2, voice: .hat, vel: 0.18),
      .init(step: 4, voice: .hat, vel: 0.26),
      .init(step: 6, voice: .hat, vel: 0.16),
      .init(step: 8, voice: .hat, vel: 0.28),
      .init(step: 10, voice: .hat, vel: 0.16),
      .init(step: 12, voice: .hat, vel: 0.26),
      .init(step: 14, voice: .hat, vel: 0.14),
      .init(step: 6, voice: .perc, vel: 0.25),
    ]),
    DrumPattern(id: "world", name: "World Perc", feel: "Hand drums", bars: 2, swing: 0.1, hits: [
      .init(step: 0, voice: .kick, vel: 0.85),
      .init(step: 7, voice: .kick, vel: 0.5),
      .init(step: 16, voice: .kick, vel: 0.8),
      .init(step: 23, voice: .kick, vel: 0.55),
      .init(step: 4, voice: .tom, vel: 0.7),
      .init(step: 12, voice: .tom, vel: 0.55),
      .init(step: 20, voice: .tom, vel: 0.75),
      .init(step: 28, voice: .tom, vel: 0.6),
      .init(step: 2, voice: .perc, vel: 0.55),
      .init(step: 3, voice: .perc, vel: 0.35),
      .init(step: 6, voice: .perc, vel: 0.6),
      .init(step: 10, voice: .perc, vel: 0.5),
      .init(step: 14, voice: .perc, vel: 0.45),
      .init(step: 18, voice: .perc, vel: 0.55),
      .init(step: 22, voice: .perc, vel: 0.4),
      .init(step: 26, voice: .perc, vel: 0.6),
      .init(step: 30, voice: .perc, vel: 0.35),
      .init(step: 8, voice: .rim, vel: 0.4),
      .init(step: 24, voice: .rim, vel: 0.45),
      .init(step: 0, voice: .hat, vel: 0.22),
      .init(step: 8, voice: .hat, vel: 0.22),
      .init(step: 16, voice: .hat, vel: 0.22),
      .init(step: 24, voice: .hat, vel: 0.22),
    ]),
  ]
  static func find(_ id: String) -> DrumPattern { all.first { $0.id == id } ?? all[0] }
}
